-- LearnJabi schema update: use Supabase Auth, user-linked progress, and safer RLS

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  created_at timestamptz default now()
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  title text not null,
  title_punjabi text,
  description text,
  icon text,
  "order" integer not null unique,
  color text,
  created_at timestamptz default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units(id) on delete cascade,
  title text not null,
  title_punjabi text,
  description text,
  "order" integer not null,
  type text not null,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  unique (unit_id, "order")
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed boolean default false,
  score integer default 0,
  completed_at timestamptz,
  created_at timestamptz default now(),
  unique (user_id, lesson_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

create index if not exists idx_lessons_unit_id on public.lessons(unit_id);
create index if not exists idx_user_progress_user_id on public.user_progress(user_id);
create index if not exists idx_user_progress_lesson_id on public.user_progress(lesson_id);
create index if not exists idx_chat_messages_user_id on public.chat_messages(user_id);
create index if not exists idx_chat_messages_created_at on public.chat_messages(created_at);

alter table public.users enable row level security;
alter table public.units enable row level security;
alter table public.lessons enable row level security;
alter table public.user_progress enable row level security;
alter table public.chat_messages enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
  on public.users
  for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
  on public.users
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Anyone can read units" on public.units;
create policy "Anyone can read units"
  on public.units
  for select
  using (true);

drop policy if exists "Anyone can read lessons" on public.lessons;
create policy "Anyone can read lessons"
  on public.lessons
  for select
  using (true);

drop policy if exists "Users can read own progress" on public.user_progress;
create policy "Users can read own progress"
  on public.user_progress
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own progress" on public.user_progress;
create policy "Users can insert own progress"
  on public.user_progress
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own progress" on public.user_progress;
create policy "Users can update own progress"
  on public.user_progress
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own chat messages" on public.chat_messages;
create policy "Users can read own chat messages"
  on public.chat_messages
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own chat messages" on public.chat_messages;
create policy "Users can insert own chat messages"
  on public.chat_messages
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own chat messages" on public.chat_messages;
create policy "Users can delete own chat messages"
  on public.chat_messages
  for delete
  using (auth.uid() = user_id);
